- 04-r.Rmd
I want to merge this because x, y, z
> Updated ggplot2 tag to be ggplot

- 08-projects.Rmd
missing learnings objectives/public. needs hyperlinks to topic explanations in the book too.
> finish stat290 proj1

- 03-sql.Rmd
- 08-projects.Rmd
forgot to create a new branch... hopefully it doesn't affect anything.
> aug 13 work

- 03-sql.Rmd
- 08-projects.Rmd
only thing left is putting the missing Book topics in the respective section. There's 27 topics to be filled in.
> relevant topics

- 02-unix.Rmd
Dear @kevinamstutz , the commands of `touch` and `rm` are mentioned in [290/390 Project 3](https://thedatamine.github.io/the-examples-book/projects.html#p03-290). Draft paragraphs are added - please feel free to modify it by adding more details. Thanks!
> Add `touch` and `rm`

- 08-projects.Rmd
> Fix typo with stat 290 project 3

- 08-projects.Rmd
Hi @kevinamstutz , I think the combination and removal of questions are fine. (I think Dr. Ward's suggestion to remove some questions from 390 was a good idea so that the students are not overloaded - I did not realize this!) 
I only modified the wording a bit to clarify things from my perspective. (For example, the use of bold fonts in p04-290-q6 was a bit crowded.) However, please feel free to accept, reject, or modify my suggestions! Thanks!
> Update wording (p04-290-q6,7; p04-390-q4,5,6)

- 08-projects.Rmd
Dear @kevinamstutz  These are the modifications I made on project 5
* I removed the statement about the while loop and if/else statement as the project does not require any of these two control flows I replaced them instead with the for loop statement.
* I removed the last line as this project does not touch on the apply function topic yet
* I rephrased  question 1 in order to clarify the fact that each year's folder in the directory "/class/datamine/data/fars" has a ACCIDENT.csv file. I also reworded the question to make it clear to the students what we meant by the year entries not being complete. 
* Personally for this question I would have asked the students to call the new column something different than "YEAR"since such a column already exists in the dataset. That way they could …
> [TheDataMine/the-examples-book] [190-p5] edits

- 08-projects.Rmd
Dear @kevinamstutz , I suggest a few modifications for 290 Project 5. Please feel free to take, modify, or reject them as needed. Thanks!
> Formatting 290-p5

- 08-projects.Rmd
Dear @kevinamstutz , I make some modifications to make Projects 5 of 290 and 390 consistent. (The 290 formatting can be found in #75 .) Please take a look if it helps. Thanks!
> Formatting 390-p5

- 08-projects.Rmd
* Question1: There was a sentence right below the dataset address in the header which I think was supposed to describe the dataset but it was formulated as a question . I removed it, instead I moved the description into question 1 and slightly rephrased question 1.
* Question2: I changed the file address from  "/class/datamine/data/states.csv" which is not the correct address to this instead "/class/datamine/data/fars/states.csv". I have also provided a brief description of the type of data this file contains. I have rephrased some of the sentences in the hint section in order to make it more clear. I have fixed the link for the helpful topics "as.factor" and "in" but I am not sure if the link will work.
* Question 3:  I have added 'which.max' to the list of relevant topic. I am not sure …
> Edits for project 6

- 08-projects.Rmd
Dear @kevinamstutz , I would like to make a few formatting changes in this pull request.
Moreover, could you double check the links in the "Dataset" section in the introduction for both 290 and 390? Currently the following links seem not to work:
* https://www.datadepot.rcac.purdue.edu/datamine/flights/subset/1987.csv
* https://www.datadepot.rcac.purdue.edu/datamine/flights/subset/YYYY.csv
Thank you!
> Formatting 290/390 Project 6

- 08-projects.Rmd
One set of potential modifications for project 6 that:
1. Keeps question 2, but rewords it to be (hopefully) more clear.
2. Adds some more stuff to question 4.
Both (1) and (2) can be removed without any problem. Thanks @mdw333!
> Dr. Ward's new project 6

- 02-unix.Rmd
Dear @kevinamstutz , I am adding some explanation for the awk array example. The motivation was that students may find Question 5 of 290 Project 7 confusing without knowing (or remembering) arrays in awk. 
However, I was only writing that explanation based on my understanding. Please feel free to modify it as you see fit! 
Also, the link in my edits was from Dr. Ward's [awk reference page](https://www.stat.purdue.edu/datamine/19000/awk.html) for 190 in Fall 2018. I am not sure whether that link is too much...
Thanks!
> Annotating awk array example

- 04-r.Rmd
- 08-projects.Rmd
Dear @kevinamstutz this is a pull request containing my edits and suggestions for Project 7 
* Question # 1: Sentence rephrasing to ensure students do not read in all interactions.csv rows after reading the first sentence of the question . Also the question asks to load the interactions.csv dataset but  none of the subsequent questions uses that dataset.  Should we still require the students to read this data in ?
* Question # 2 : No edits for this question
* Question # 3 : No edits for this question
* Question # 4: This question is not clear. I do not think students will be able to understand what the question is asking them to do based on the wording.
We have not yet introduced what a list is formally to the students hence the structure of the data they get after the split function …
> [Stat 1900 Project # 7 ] Edit suggestions

- 08-projects.Rmd
Dear @kevinamstutz , I include a few suggestions for updating Project 8 of 290 and 390. I will include inline comments explaining my suggestions. Thanks!
> Update description of 290/390-p8

- 08-projects.Rmd
Dear @kevinamstutz , sorry for getting in Project 9 suggestions this late! I will add my reasons for the wording suggestions. Please feel free to modify or ignore them as you see fit. Thanks!!
> Suggestions for wording 290/390-p9

- 08-projects.Rmd
Hello @kevinamstutz here are my edits for project 9 
* Question # 1: The package "imager" was not installed on my R session and most students would not have it installed and will therefore get an error when running the function. I added a note before question one that asked them to download the package. 
I rephrased part of the question to provide students with more guideline on how to get a book_id. 
Also, changed the phrasing to tell them to try until they get exactly 2 successes. I think that makes for less room for ambiguity.
* Question # 2: slight sentence rephrasing
* Question # 3:  slight sentence rephrasing
* Question #  4:  slight sentence rephrasing
* Question # 5: nothing to change.
> [STAT 1900 project # 9] Edits and suggestions

- 08-projects.Rmd
Hey @mdw333, could you take a look at the modification I made to Question 4/5? One of @ymzhang-neo questions made me realize we changed question 4 in a manner which "ruins" question 5, as question 5 requires they have the data for all of the years. Thank you!
> Fix p8 39000

- 04-r.Rmd
Dear @kevinamstutz, as mentioned in the comments of the previous pull request (#123). I have updated the R-resources section to include the documentation and examples for the strrep and nchar functions.
> [STAT 1900- R resource] Adding strrep and nchar

- 08-projects.Rmd
**Scope** : a small edit;  replaced r with R
**Question 1:** Added the links for the relevant topics  strrep and nchar. ( I will be adding the section for those 2 functions in the example book in another pull request)
**Question 2:** NA
**Question 3:** Should we specify that we would like to see the two line graphs on the same plot?
**Question 4:** 
- In the hint section for this question students are told to refer to the use of the function  "plot_usmap" in question 6 of project 6 to learn how to create the map. However no such function was used in the solution section of question 6 project 6. I also browsed through the entire example book and could not find any reference of the function "plot_usmap" in the Stat 1900, 2900 nor 3900 projects.
-  I also added the items to submit box and …
> [STAT 1900- project 11] Edits and Suggestions

- 08-projects.Rmd
Dear @kevinamstutz , sorry for getting the feedback for Project 12 a bit late! Please see the changes that I suggest in the pull request. I will also add comments explaining some of the suggestions. Thanks!!
> [290/390-p12] Wording suggestion

- 08-projects.Rmd
Dear @kevinamstutz please find below the edits I am suggesting for project 12 
**Question 1**:  NA
**Question 2**: small grammatical edit
**Question 3:** NA 
**Question 4** : NA 
**Question 5**:  fixed the name of the new data. Changed it from `states2008plus` to `states2010plus` to match the data name defined in the previous sentence.
**Question 6**:  removed repeated word  and reworded one of the sentences.
> [STAT 1900 --- project 12] Minor Edits

- 04-r.Rmd
Dear @kevinamstutz, as mentioned in the comments for pull request # 132, I have added a small example and description of the `fread` function in the R documentation under the **Reading & Writing data** section.
> [stat 1900 - R documentation] fread function example and description

- 08-projects.Rmd
Dear @kevinamstutz , please find below the edits suggestions I have for project 14. This pull request will be followed by another in which I edit the example book to add descriptions for the functions `setdiff` and `intersect`.
**Question # 1:** 
- Added the link for ` the function `fread` in the relevant topic section.
- Added a link for the function `setdiff` and will be adding a section in the R section of the example book using another pull request.
- Also fixed small grammatical errors within the question's paragraph.
**Question # 2**: Added the link for the function `in` in the relevant topic section. Some minor sentence changes.
**Question # 3**: Added a link for the function `intersect` and will be adding a section in the R section of the example book.
**Question # 4**: Added the …
> [Stat 1900 - project 14] Edits

- 04-r.Rmd
Dear @kevinamstutz  this pull request complement the pull request #140  for project 14 .
I added descriptions and examples for the functions `setdiff` and `intersect` in the R section of the example book.
> [stat 1900 - Example book R]  Functions addition

- 08-projects.Rmd
Dear @kevinamstutz , sorry for getting this set of suggestions late for Project 14 (on the same day as Project 15)!! As usual, I will add annotation to some of the changes.
Meanwhile, I will attempt the `ggmap`-related questions once the API issue is fixed (mentioned in #136 ).
Thanks so much!
> [290/390-P14] Suggestions

- 08-projects.Rmd
Dear @kevinamstutz , here are some suggestions I have for Projects 15 of 290 and 390. I will add annotation to some of the changes. Thank you!
> [290/390-P15] Suggestion

- 08-projects.Rmd
Dear @kevinamstutz please find below the edits I suggest for project 15.
**Question 1:**  
- Since we instructed students to convert the `data.table` format into a `data.frame` format when reading the data in, I do not think the hint about adding quotes to access column which have space in their name is necessary. Converting the data to a `data.frame` inserts dots where there were spaces. What do you think ? I left the hint there for now.
- Made some small edits
- Added the link for the function `fread` in the relevant topic section.
**Question 2:**  
- Added link for the `difftime` in the relevant topic section and will be editing the example book to add a description of that function in  another pull request.
- Rephrased some of the hint sentences.
**Question 3**:  corrected typos in …
> [Stat 1900- project 15] Edits

- 04-r.Rmd
Dear @kevinamstutz, in this pull request I edited the R section of the example book to add a section for the function `difftime`. This pull request complements pull request #142  of project 15.
> [STAT 1900- example book R] addition of difftime

- 02-data-formats.Rmd
- 09-projects.Rmd
Story details: https://app.clubhouse.io/thedatamine/story/55
> Write Spring 2021 project 3 draft

- 09-projects.Rmd
Dear @kevinamstutz , I found very few edits to make on this project.
**Question 1**: NA
**Question 2**: NA
**Question 3**: I rephrased part of the question to reflect the way I understood it. I am not sure whether that was what was meant or not.
**Question 4**: I personally don't see a big difference in the shape of the plot with or without the last 50 values. The y-axis scale changes but the shape of the plot remains the same.
**Question 5**: NA
> STAT 19000 Project 2: Edits

- 09-projects.Rmd
**Question 1 :** added a link to the python head() function within the example book.
**Question 2 :**  NA
**Question 3 :** added a direct link to the matplotlib barplot.
**Question 4 :**  Slightly changed the wording of the last sentence in the question to make it obvious to students that they should recode all three examples.
**Question 5 :**  
- **Part 1** -- I tried this question and for constructing the dictionary I could not get the code to work without using the `setdefault()` function which we have not introduced to the students. I am not sure if I am the one who can't think of a way of not using this function but I tried without it and it wouldn't let me append values to a specific key in the dictionary otherwise.  Here is the code I worked with 
` # for each year (key),long and …
> STAT 19000 Project 3 edits

- 06-python.Rmd
Dear @kevinamstutz , I have added a section in the python part of the example book for the pandas function `to.csv`.
> Example book Python section update

- 09-projects.Rmd
Dear @kevinamstutz going back through the project I thought it would help the students to know about the `to.csv` function for question 1.  I have also updated the python section of the book to describe how this function works.
Thank you
> STAT 19000: Project 5 Minor Edit 

- 09-projects.Rmd
**Question 1:** 
- Fixed a small typo. 
- I do not understand the hint provided. Is there a need for a percentage to solve the question?
**Question 2:** 
- Added the word `train` to clarify the reference made later in the paragraph.
- I do not believe the Stat 19000 students were introduced to the `tidyverse` package last year. I think it would be good to first show the `tapply` function example before the `tidyverse` one so I switched their position. 
- I am not sure about the need to mention the  `cosine_similarity_matrix` for this question.
**Question 3-4:** Should we ask them to print the head and/or shape of the resulting DataFrame ? I have added that in the item to submit box.
> STAT 19000 Project 9 review

- 09-projects.Rmd
Dear @kevinamstutz please find bellow the edits for project 10.
**Question 1:** small grammatical changes
**Question 2 :** 
- Small change in phrasing question 
- Added an example for them to test their function
**Question 3:**  Punctuation change and added one more item to submit
**Question 4:**  small addition to bullet #1 
**Question 5 :** NA
> STAT 19000 Project 10 Review

- 09-projects.Rmd
Dear @kevinamstutz, I only have one edit for this project.
**Question 1:** In the item to submit box, changed the "output from running your code" to "head of the accidents dataframe".
**Question 2-5:** NA
Thank you
> STAT 19000 Project 11: Edits

- content/modules/python/pages/indentation.adoc
This branch was David's first attempt at creating a page in the examples book. The page was moving material focused on the importance of indentation in Python.
> Create Python Indentation Page

- content/modules/python/pages/variables.adoc
Updating the Python variables page based on the previous examples book entry. Also added a section for NaN values for student reference.
> Add python variables page

- content/modules/python/pages/printing-and-f-strings.adoc
Updating the content page for printing and f-strings. I also pulled escape characters into its own subsection on the page.
> Adding page for Python printing and f-strings.

- content/modules/python/pages/lists.adoc
- content/modules/python/pages/tuples.adoc
Adding a document page for Python lists. I also added a indexing link to the Tuples page.
> Add python lists page

- content/modules/projects/pages/19000-f2021-project02.adoc
> formatting fix

- content/modules/python/pages/pandas-aggregate-functions.adoc
- content/modules/python/pages/pandas-dataframes.adoc
- content/modules/python/pages/pandas-dates-and-times.adoc
- content/modules/python/pages/pandas-indexing.adoc
- content/modules/python/pages/pandas-reshaping.adoc
- content/modules/python/pages/pandas-series.adoc
Creating the content pages for the Python Pandas sections.
> Python pandas pages

- antora-playbook.yml
- content/modules/ROOT/pages/introduction.adoc
removed agile trainings repo due to mistake of repo ownership
> remove agile appendix

- content/modules/projects/nav.adoc
- content/modules/projects/pages/s2022-schedule.adoc
- content/modules/projects/pages/s2022-syllabus.adoc
Added s2022 seminar syllabus. Will add course schedule once dates are finalized.
> spring2022-syllabus-seminar

- content/modules/python/nav.adoc
- content/modules/python/pages/dask.adoc
Adding documentation for launching a Dask dashboard.
> Dask Documentation

- content/modules/projects/pages/19000-f2021-project01.adoc
HI KEVIN MICROSOFT IS NOT A TEXT EDITOR
> Plain English Edits

- content/modules/r/nav.adoc
- content/modules/r/pages/r-base-functions.adoc
- content/modules/r/pages/r-grep.adoc
Added content for grep as used in R, as well as some connected functions. Changed the necessary navigation adocs - let me know if any were missed.
> Created r-grep.adoc page

- content/modules/python/pages/requests.adoc
Copied requests into the new examples book, nearly 1:1, just some grammatical changes
> Created requests.adoc from old examples book

- content/modules/python/pages/selenium.adoc
Created the adoc for the selenium content we needed. A few notes:
- I highlighted part of the note (at line 63) that referenced ThinLinc. I wasn't sure if that was correct or if it needed to be changed to Brown. I also wasn't 100% that it was our old cluster, I just took a guess haha.
- There were a few points in the lengthy last example where I wanted to link to the Code and Example sections, though I wasn't sure how to do it. If you think it's worthwhile I'll add them
> [INS-257 PR] Moved selenium.adoc from old book

- content/modules/python/pages/dictionaries.adoc
Moved over the dictionaries page with some enhancements
> [INS 243 Drew Sukova] Created dictionaries.adoc from old book content

- content/modules/r/pages/max.adoc
Created max.adoc for R with a few edge examples
> [INS 216 Drew Sukova] Created max.adoc

- content/modules/r/pages/length.adoc
Moved over the length page, adding an example about nchar for thoroughness
> [INS 217 Drew Sukova] Created length.adoc from old book

- content/modules/r/pages/which.adoc
Created which.adoc documentation from old examples book
> INS-221-Dania-Khan

- content/modules/r/pages/var.adoc
> INS-211-Dania-Khan

- content/modules/r/pages/rep.adoc
Moved rep.adoc to new examples book
> INS-219-Dania-Khan

- content/modules/r/pages/mean.adoc
Second time trying to upload this document so ignore any previous branch (I tried to delete it so hopefully there's no doubles!)
> INS-209-Dania-Khan

- content/modules/r/pages/paste-and-paste0.adoc
Moved paste-and-paste0 from old examples book to the new one for R
> INS-224-Dania-Khan

- content/modules/python/pages/control-flow.adoc
Overhauled the control flow page. Removed some examples and demonstrations that I felt interfered with the flow of the page, let me know if you're partial to any of the ones I removed. Thanks!
> [INS-246 Drew Sukova] Created control-flow.adoc from old book

- content/modules/python/pages/lxml.adoc
Transferred old lxml page to new Examples Book, enhanced some grammar and examples.
> [INS-255 Drew Sukova] Created lxml.adoc from old book

- content/modules/python/pages/classes.adoc
Transferred Python classes page to new book from the old examples book in asciidoc
> Transferred Python classes page to new book

- content/modules/r/pages/data-frames.adoc
Moved the old Examples Book content to the new Examples Book, making minor revisions for flow. I was looking for a grep page to link on the final example, but I didn't see one in R base functions. Is it elsewhere or is that a page that still needs moved over?
> [INS 199 Drew Sukova] created data-frames.adoc from R content

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/min.adoc
> INS-215-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/merge.adoc
Moved merge.adoc from old examples book to new one for R
> INS-228-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/python/pages/sets.adoc
Enhanced the sets.adoc page, adding an introduction, implementation, and examples.
> [INS 244 Drew Sukova] Created sets.adoc

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/cut.adoc
Moved cut for r from old examples book to the new one
> INS-225-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/order.adoc
Moving order section from old examples book to new one
> INS-223-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/sort.adoc
Moved sort info from old examples book to new one
> INS-222-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/r/nav.adoc
- content/modules/r/pages/table-and-prop-table.adoc
table and prop.table data to new examples book
> INS-218-Dania-Khan

- _redirects
- antora-playbook-preview.yml
- content/modules/r/pages/unique.adoc
adding unique data to new examples book
> INS-207-Dania-Khan

- book/modules/gallygoogle/pages/introduction.adoc
- book/modules/gallygoogle/pages/wordcloud.adoc
deleted word cloud repeat portion and added edited the welcome page
> Edited two pages nothing big

- programming-languages/modules/R/pages/head.adoc
Adjusted indentation on document, fixed erroneous statement that default was `n = 10` in R
> [INS-205-drew-sukova] fixed head.adoc

- programming-languages/modules/R/pages/abs.adoc
Added abs.adoc to R base functions
> [INS 213 Drew Sukova] created abs.adoc

- programming-languages/modules/R/nav.adoc
- programming-languages/modules/R/pages/table-and-prop-table.adoc
Changed the name of the table page in nav.adoc, edited content within page itself
> [INS 218 Drew Sukova] minor table-and-prop-table.adoc changes

- programming-languages/modules/R/pages/seq.adoc
Created new seq.adoc from R documentation
> [INS 220 Drew Sukova] Create seq.adoc

- programming-languages/modules/R/pages/order.adoc
Added another example and clarified the difference between order and sort
> [INS 223 Drew Sukova] Update order.adoc

- programming-languages/modules/R/pages/merge.adoc
Adjusted some typos, indentation level, and examples. Did not include output for some code as Brown was offline for maintenance
> [INS 228 Drew Sukova] updated merge.adoc

- programming-languages/modules/R/pages/data-frames.adoc
Fixed the weird nesting issue that happened between different PRs/merges, updated some sections
> [INS 236 Drew Sukova] fixed data-frames.adoc

- data-engineering/modules/rcac/nav.adoc
- data-engineering/modules/rcac/pages/anvil.adoc
Adding a page to provide additional information about Anvil and XSEDE.
> Anvil Content

- book/modules/ROOT/pages/introduction.adoc
- book/modules/ROOT/pages/tdm-intro-transcript.adoc
Adding a transcript for the TDM introduction video on the main page.
> Intro Video Transcript

- programming-languages/modules/python/pages/writing-scripts.adoc
Moved Python script-writing from old book, added script vs library section, explained parts of `bash` that are not included in new book.
**Please correct if script/module/package/library content is misleading**. I think I grasped the nuances but there were a lot of different sources saying slightly different things.
> [INS 249 Drew Sukova] Moving & enhancing writing-scripts.adoc

- programming-languages/modules/python/pages/classes.adoc
Decreased bold font, fixed spacing and header levels, changed organization of page
> [INS 248 Drew Sukova] overhauled classes.adoc

- corporate-partners-appendix/modules/students/pages/fall2022/final_presentation.adoc
Final Presentation are to be kept confidential.
> Final Presentation Warning

- corporate-partners-appendix/modules/mentors/nav.adoc
- corporate-partners-appendix/modules/mentors/pages/data-science-guide.adoc
- corporate-partners-appendix/modules/mentors/pages/technicalresources.adoc
This document is designed to help mentors when starting their collaboration with the DS team.
> Pushing Initial DS Collab Doc

- corporate-partners-appendix/modules/mentors/nav.adoc
- corporate-partners-appendix/modules/mentors/pages/data-science-project.adoc
- corporate-partners-appendix/modules/mentors/pages/data-science-sponsored-research.adoc
- projects-appendix/modules/current-projects/pages/30100-2022-project11.adoc
Developing content to help mentors when scoping a Data Mine project.
> Adding Project Scoping

- projects-appendix/modules/current-projects/pages/20200-2023-project10.adoc
Thought this was a good addition for our students.
> Added link to useful docs in question 3

- starter-guides/modules/anvil/nav.adoc
- starter-guides/modules/anvil/pages/access-email-update.adoc
- starter-guides/modules/anvil/pages/other-user-setup.adoc
- starter-guides/modules/anvil/pages/purdue-user-setup.adoc
Adding steps for users to associate their ACCESS account with their edu email.
> Updating for TDM Automation

- corporate-partners-appendix/modules/students/pages/ds_team_support.adoc
Adding documentation for the process to schedule a DS team review for student teams.
> DS Team Contact

- corporate-partners-appendix/modules/mentors/pages/data-usage-framework.adoc
Updating the document content based on feedback from Purdue Legal.
> Purdue Legal Updates

- starter-guides/modules/anvil/nav.adoc
- starter-guides/modules/anvil/pages/access-helpful-links.adoc
Adding helpful hyperlinks for the functions to remember an ACCESS ID and reset the password.
> ACCESS ID/Pass Links

- corporate-partners-appendix/modules/students/pages/spring2024/ms_team.adoc
- starter-guides/modules/anvil/pages/access-helpful-links.adoc
- starter-guides/modules/anvil/pages/general-user-setup.adoc
- starter-guides/modules/anvil/pages/other-user-setup.adoc
- starter-guides/modules/anvil/pages/purdue-user-setup.adoc
Adding documentation to address:
- Failed to map user error
- Teams sync timeframe
- ACCESS survey timeframe
> Updating Tech Tips

- programming-languages/modules/python/nav.adoc
- programming-languages/modules/python/pages/python-starter-skills-roadmap.adoc
- starter-guides/modules/languages/nav.adoc
The initial skills roadmap is designed to help students with no background in Python learn the core topics to work on TDM CRP projects on Anvil.
> First Draft Python Skills Roadmap

- corporate-partners-appendix/modules/TAs/pages/fall2024/explicit_all_sprints.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/fall_wrap_up.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/final_presentation.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/pre_fall_prep.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/responsibilities.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/schedule.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint1.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint2.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint3.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint4.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint5.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint6.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2024/sprint7.adoc
changes to fall 2024 TA section
> changes to fall 2024 TA section

- corporate-partners-appendix/modules/students/pages/spring2025/crp_networking_event.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/final_presentation_tips.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/finalreport.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/index.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/locations.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/ms_team.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/poster_guidelines.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/questions.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/schedule.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/spring2025_symposium_expectations.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint1.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint2.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint3.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint4.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint5.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint6.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint7.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/syllabus.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/syllabus_purdue_policies.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/symposium_day_of_guidelines.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/video_guidelines.adoc
Amanda will start to prepare the s25 professional development content
> spring 2025 content

- corporate-partners-appendix/modules/TAs/pages/spring2025/pre_spring_prep.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/responsibilities.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/schedule.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint1.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint2.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint3.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint4.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint5.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint6.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint7.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/symposium_how_to_prepare_the_team.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/symposium_ta_expectations.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/symposium_youtube.adoc
> TA content for spring 2025

- corporate-partners-appendix/antora.yml
- corporate-partners-appendix/modules/advisors/nav.adoc
- corporate-partners-appendix/modules/advisors/pages/index.adoc
One-pager for information surrounding corporate partner faculty advisors.
> CRP Advisor Page

- corporate-partners-appendix/modules/TAs/nav.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/schedule.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/syllabus.adoc
added student schedule, TA list to syllabus in student spring 2025 section + moved fall 2024 to archive in TA section
> added student schedule, TA list to syllabus in student spring 2025 

- corporate-partners-appendix/modules/TAs/nav.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/pre_spring_prep.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/responsibilities.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/schedule.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint1.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint4.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint6.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/sprint7.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/symposium_how_to_prepare_the_team.adoc
- corporate-partners-appendix/modules/TAs/pages/spring2025/symposium_youtube.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/schedule.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/syllabus.adoc
updated the Spring 2025 section in the TA block and updated information upto sprint 1. Placed under construction for the rest.
> updated the Spring 2025 section in the TA block

- corporate-partners-appendix/modules/students/pages/spring2025/poster_guidelines.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/spring2025_symposium_expectations.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint1.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint2.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint3.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint4.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint5.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint6.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/sprint7.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/symposium_day_of_guidelines.adoc
- corporate-partners-appendix/modules/students/pages/spring2025/video_guidelines.adoc
updated dates
removed construction notes
improved formatting
> updates to all sprint pages

- corporate-partners-appendix/modules/TAs/pages/fall2025/fall_wrap_up.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint2.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint3.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint4.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint5.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint6.adoc
- corporate-partners-appendix/modules/TAs/pages/fall2025/sprint7.adoc
To reflect changes made in the TA schedule in google docs
> Updating dates in the TA section

- corporate-partners-appendix/modules/projectmanagement/pages/intro.adoc
First module updated, link for the hybrid image created within the content(image::https://the-examples-book.com/crp/projectmanagement/_images/hybrid.png[width=250]), Sources are still TBD.
> Update intro.adoc  (Introduction to Project Management)

- corporate-partners-appendix/modules/projectmanagement/pages/ceremonies.adoc
updated ceremonies based on the document
> Update ceremonies.adoc (Module 2.2: Ceremonies)
